CREATE DATABASE `orgdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE TABLE `DEDUCCIONESOBRERO` (
  `FECHA` date NOT NULL,
  `CEDULA` mediumint NOT NULL,
  `CCSS` double NOT NULL,
  `BANCOPOPULAR` double NOT NULL,
  `ASOCIACIONSOLIDARISTA` double DEFAULT NULL,
  PRIMARY KEY (`FECHA`,`CEDULA`),
  KEY `DEDUCCIONOBRERO_EMPLEADO_idx` (`CEDULA`),
  CONSTRAINT `DEDUCCIONOBRERO_EMPLEADO` FOREIGN KEY (`CEDULA`) REFERENCES `EMPLEADO` (`CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `DEDUCCIONESPATRONALES` (
  `FECHA` date NOT NULL,
  `CEDULA` mediumint NOT NULL,
  `CCSS` double NOT NULL,
  `AGUINALDO` double NOT NULL,
  `CESANTIA` double NOT NULL,
  `VACACIONES` double NOT NULL,
  `RIESGOTRABAJOINS` double NOT NULL,
  PRIMARY KEY (`FECHA`,`CEDULA`),
  KEY `DEDUCCIONESPATRONALES_EMPLEADO_idx` (`CEDULA`),
  CONSTRAINT `DEDUCCIONESPATRONALES_EMPLEADO` FOREIGN KEY (`CEDULA`) REFERENCES `EMPLEADO` (`CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `EMPLEADO` (
  `CEDULA` mediumint NOT NULL,
  `ISACTIVE` tinyint NOT NULL,
  `NOMBRE` char(45) NOT NULL,
  `APELLIDO1` char(45) NOT NULL,
  `APELLIDO2` char(45) NOT NULL,
  `SALARIO` double NOT NULL,
  PRIMARY KEY (`CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PARTICIPACIONAS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CEDULA` mediumint NOT NULL,
  `PORCENTAGE` tinyint NOT NULL,
  PRIMARY KEY (`ID`,`CEDULA`),
  KEY `PARTICIPACION_EMPLEADO_idx` (`CEDULA`),
  CONSTRAINT `PARTICIPACION_EMPLEADO` FOREIGN KEY (`CEDULA`) REFERENCES `EMPLEADO` (`CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PLANILLAEMPLEADO` (
  `NPLANILLA` int NOT NULL AUTO_INCREMENT,
  `CEDULA` mediumint NOT NULL,
  `DEDUCCIONESOBRERO` double NOT NULL,
  `DEDUCCIONESPATRONALES` double NOT NULL,
  `IMPUESTORENTASALARIO` double NOT NULL,
  `SALARIOBRUTO` double NOT NULL,
  `SALARIOTOTAL` double NOT NULL,
  `FECHA` date NOT NULL,
  `REPORTE` varchar(64) NOT NULL,
  PRIMARY KEY (`NPLANILLA`),
  KEY `PLANILLA_EMPLEADO_idx` (`CEDULA`),
  CONSTRAINT `PLANILLA_EMPLEADO` FOREIGN KEY (`CEDULA`) REFERENCES `EMPLEADO` (`CEDULA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
